KorsatkoApp/Controllers/PaymentController.cs
using KorsatkoApp.Areas.Admin.Models;
using KorsatkoApp.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NToastNotify;

namespace KorsatkoApp.Controllers {
	[Authorize]
	public class PaymentController : Controller {
		private readonly IToastNotification _toastNotification;
		private readonly UserManager<Student> _UserManager;
		private readonly ApplicationDbContext _context;

		public PaymentController(IToastNotification toastNotification, UserManager<Student> userManager, ApplicationDbContext context) {
			_toastNotification = toastNotification;
			_UserManager = userManager;
			_context = context;
		}

		public IActionResult Index() {
           string sessionid = HttpContext.Request.Query["sessionid"];
           string courseid = HttpContext.Request.Query["courseid"];

            ViewBag.sessionid = sessionid;
            ViewBag.courseid = courseid;
            return View();
		}


        public async Task<IActionResult> Confirm() {
           string sessionid = HttpContext.Request.Query["sessionid"];
           string courseid = HttpContext.Request.Query["courseid"];
			var student = await _UserManager.FindByEmailAsync(User.Identity.Name);
			var studentid = student.Id;
			Enrollment enrollment = new Enrollment() {
				PaymentStatus="تم الدفع",
				SessionId=int.Parse(sessionid),
				StudentId= studentid,
				EnrollmentNumber = Guid.NewGuid().ToString(),
				AddedOn = DateTime.Now
		};


			_context.Add(enrollment);
			await _context.SaveChangesAsync();
			_toastNotification.AddSuccessToastMessage("تمت اضافة اللإشتراك بنجاح");

			return RedirectToAction("Index", "MyCourses");
        }
    }
}

KorsatkoApp/Views/Payment/Index.cshtml
@{
	Layout = "_LoggedInLayout";
}
<div class="content-wrapper" style="min-height: 70vh;">
	<div class="px-3 mt-4 mb-5 pb-3">
		<form class="card mx-auto" style="max-width: 500px;">
			<div class="card-body py-4">
				<h3 class="text-center mb-4">تأكيد عملية الدفع</h3>

				<div class="row gy-3">
					<div class="col-12">
						<label class="form-label">الاسم المسجل على البطاقة</label>
						<input type="text" class="form-control">
						<span class="form-text text-danger"></span>
					</div>

					<div class="col-12">
						<label class="form-label">رقم البطاقة</label>
						<input class="form-control" type="text" maxlength="16">
						<span class="form-text text-danger"></span>
					</div>

					<fieldset class="col-12 col-sm-7">
						<label class="form-label">تاريخ الإنتهاء</label>

						<div class="row g-1">
							<div class="col-6">
								<select class="form-select">
									<option value="01">يناير</option>
									<option value="02">فبراير</option>
									<option value="03">مارس</option>
									<option value="04">أبريل</option>
									<option value="05">مايو</option>
									<option value="06">يونيو</option>
									<option value="07">يوليو</option>
									<option value="08">أغسطس</option>
									<option value="09">سبتمبر</option>
									<option value="10">أكتوبر</option>
									<option value="11">نوفمبر</option>
									<option value="12">ديسمبر</option>
								</select>
							</div>

							<div class="col-6">
								<select class="form-select">
									@for (int i = 0; i < 10; i++)
									{
										<option>@(DateTime.Now.Year + i)</option>
									}
								</select>
							</div>
						</div>
					</fieldset>

					<div class="col-12 col-sm-5">
						<label class="form-label">رمز التحقق (CVV)</label>
						<input type="text" class="form-control" maxlength="3">
						<span class="form-text text-danger"></span>
					</div>

					<div class="col-12">
						<div class="form-check">
							<input class="form-check-input" type="checkbox">
							<label class="form-check-label form-text">
								تذكر البطاقة في عمليات الدفع المستقبلية
							</label>
						</div>
					</div>
				</div>
			</div>

			<div class="card-footer">
				<a asp-area="" asp-controller="Payment" asp-action="Confirm" asp-route-courseid="@ViewBag.courseid" asp-route-sessionid="@ViewBag.sessionid" class="btn btn-primary">تأكيد</a>
				<a class="btn btn-danger">إلغاء</a>
			</div>
		</form>
	</div>
</div>