KorsatkoApp/Controllers/MyCoursesController.cs
using KorsatkoApp.Areas.Admin.Models;
using KorsatkoApp.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace KorsatkoApp.Controllers {
	[Authorize(Roles ="User")]
	public class MyCoursesController : Controller {
		private readonly ApplicationDbContext _context;

		public MyCoursesController(ApplicationDbContext context) {
			_context = context;
		}
		public IActionResult Index() {
			var enrolls = _context.Enrollments
				.Include(e => e.student)
				.Include(e => e.session)
				.ThenInclude(e => e.course)
				//.Include(e => e.session)
				//.ThenInclude(e => e.instructor)
				.Where(e => e.student.Email == User.Identity.Name).ToList();
			return View(enrolls);
		}

		public async Task<IActionResult> Sessions()
		{
			IEnumerable<Enrollment> enrolls = await _context.Enrollments
				.Include(e => e.student)
				.Include(e => e.session)
				.ThenInclude(e => e.course)
				.Include(e => e.session)
				.ThenInclude(e => e.instructor)
				.Where(e => e.student.Email == User.Identity.Name).ToListAsync();

			return View(enrolls);
		}
	}
}

KorsatkoApp/Controllers/MyProfileController.cs
using KorsatkoApp.Data;
using KorsatkoApp.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace KorsatkoApp.Controllers
{
    [Authorize]
    public class MyProfileController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MyProfileController(ApplicationDbContext context) {
            _context = context;
        }

        // GET: MyProfileController
        public ActionResult Index()
        {
            var student = _context.Users
                .Where(e => e.Email == User.Identity.Name)
                .First();

            return View(student);
        }
    }
}

KorsatkoApp/Views/Shared/_FooterPartial.cshtml
<footer class="footer text-bg-dark text-center text-md-start">
    <div class="container-md p-sm-2 p-md-3">
        <div class="row">
            <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-4">
                <h3>الروابط</h3>

                <ul class="nav flex-column align-items-center align-items-md-start">
                    <li class="nav-item">
                        <a asp-area="" asp-controller="Home" asp-action="Index"
                           class="nav-link @(ViewBag.activeNavbarItem == "home" ? "active" : "")">
                            الصفحة الرئيسية
                        </a>
                    </li>
                    <li class="nav-item">
                        <a asp-area="" asp-controller="Home" asp-action="Courses"
                           class="nav-link @(ViewBag.activeNavbarItem == "courses" ? "active" : "")">
                            الدورات
                        </a>
                    </li>
                    <li class="nav-item">
                        <a asp-area="" asp-controller="Home" asp-action="Instructors"
                           class="nav-link @(ViewBag.activeNavbarItem == "instructors" ? "active" : "")">
                            المدربين
                        </a>
                    </li>
                    <li class="nav-item">
                        <a asp-area="" asp-controller="Home" asp-action="AboutUs"
                           class="nav-link @(ViewBag.activeNavbarItem == "aboutUs" ? "active" : "")">
                            من نحن
                        </a>
                    </li>
                </ul>
            </div>
                                     
            <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-4">
                <h3>من نحن</h3>
                <p class="col-8 col-sm-10 mx-auto mx-md-0 text-start">
                    كورساتكو هو مركز تدريبي هدفة الارتقاء بالمستوى المهاري في مجال تطوير البرمجيات في مصر.
                </p>
            </div>

            <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-4">
                <h3>تواصل معنا</h3>

                <h5>العنوان</h5>

                <p>29 شارع عدلي، وسط المدينة</p>
                <p>القاهرة - مصر</p>

                <h5 class="mt-4">رقم التليفون</h5>

                <p class="ltr-right-md">(+20) 220302481</p>
                <p class="ltr-right-md">(+20) 1098220026</p>
            </div>

            <div class="col-12 col-sm-6 col-md-12 col-lg-3 pb-4 text-center text-lg-start">
                <h3>تابعنا</h3>

                <div class="icons">
                    <a href="#">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="#ffffff" viewBox="0 0 512 512">
                            <path d="M504 256C504 119 393 8 256 8S8 119 8 256c0 123.78 90.69 226.38 209.25 245V327.69h-63V256h63v-54.64c0-62.15 37-96.48 93.67-96.48 27.14 0 55.52 4.84 55.52 4.84v61h-31.28c-30.8 0-40.41 19.12-40.41 38.73V256h68.78l-11 71.69h-57.78V501C413.31 482.38 504 379.78 504 256z" />
                        </svg>
                    </a>
                    <a href="#">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="#ffffff" viewBox="0 0 448 512">
                            <path d="M224.1 141c-63.6 0-114.9 51.3-114.9 114.9s51.3 114.9 114.9 114.9S339 319.5 339 255.9 287.7 141 224.1 141zm0 189.6c-41.1 0-74.7-33.5-74.7-74.7s33.5-74.7 74.7-74.7 74.7 33.5 74.7 74.7-33.6 74.7-74.7 74.7zm146.4-194.3c0 14.9-12 26.8-26.8 26.8-14.9 0-26.8-12-26.8-26.8s12-26.8 26.8-26.8 26.8 12 26.8 26.8zm76.1 27.2c-1.7-35.9-9.9-67.7-36.2-93.9-26.2-26.2-58-34.4-93.9-36.2-37-2.1-147.9-2.1-184.9 0-35.8 1.7-67.6 9.9-93.9 36.1s-34.4 58-36.2 93.9c-2.1 37-2.1 147.9 0 184.9 1.7 35.9 9.9 67.7 36.2 93.9s58 34.4 93.9 36.2c37 2.1 147.9 2.1 184.9 0 35.9-1.7 67.7-9.9 93.9-36.2 26.2-26.2 34.4-58 36.2-93.9 2.1-37 2.1-147.8 0-184.8zM398.8 388c-7.8 19.6-22.9 34.7-42.6 42.6-29.5 11.7-99.5 9-132.1 9s-102.7 2.6-132.1-9c-19.6-7.8-34.7-22.9-42.6-42.6-11.7-29.5-9-99.5-9-132.1s-2.6-102.7 9-132.1c7.8-19.6 22.9-34.7 42.6-42.6 29.5-11.7 99.5-9 132.1-9s102.7-2.6 132.1 9c19.6 7.8 34.7 22.9 42.6 42.6 11.7 29.5 9 99.5 9 132.1s2.7 102.7-9 132.1z" />
                        </svg>
                    </a>
                    <a href="#">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="#ffffff" viewBox="0 0 512 512">
                            <path d="M459.37 151.716c.325 4.548.325 9.097.325 13.645 0 138.72-105.583 298.558-298.558 298.558-59.452 0-114.68-17.219-161.137-47.106 8.447.974 16.568 1.299 25.34 1.299 49.055 0 94.213-16.568 130.274-44.832-46.132-.975-84.792-31.188-98.112-72.772 6.498.974 12.995 1.624 19.818 1.624 9.421 0 18.843-1.3 27.614-3.573-48.081-9.747-84.143-51.98-84.143-102.985v-1.299c13.969 7.797 30.214 12.67 47.431 13.319-28.264-18.843-46.781-51.005-46.781-87.391 0-19.492 5.197-37.36 14.294-52.954 51.655 63.675 129.3 105.258 216.365 109.807-1.624-7.797-2.599-15.918-2.599-24.04 0-57.828 46.782-104.934 104.934-104.934 30.213 0 57.502 12.67 76.67 33.137 23.715-4.548 46.456-13.32 66.599-25.34-7.798 24.366-24.366 44.833-46.132 57.827 21.117-2.273 41.584-8.122 60.426-16.243-14.292 20.791-32.161 39.308-52.628 54.253z" />
                        </svg>
                    </a>
                </div>
            </div>
        </div>

        <div class="text-center py-2 copy-notice">
            حقوق الطبع والنشر © 2023 Korsatko. جميع الحقوق محفوظة.
        </div>
    </div>
</footer>

KorsatkoApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<Student> SignInManager
@inject UserManager<Student> UserManager


<!doctype html>
<html lang="ar" dir="rtl">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cairo&family=Noto+Kufi+Arabic:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/website/css/bootstrap.rtl.min.css">
    <!-- FontAwesome -->
    <link rel="stylesheet" href="~/website/plugins/fontawesome6/css/fontawesome.min.css">
    <link rel="stylesheet" href="~/website/plugins/fontawesome6/css/regular.min.css">
    <link rel="stylesheet" href="~/website/plugins/fontawesome6/css/solid.min.css">

    @await RenderSectionAsync("Styles", required: false)

    <!-- Website CSS -->
    <link rel="stylesheet" href="~/website/css/style.css">

    <title>@(ViewData["Title"] == null ? "كورساتكو" : (ViewData["title"] + " - كورساتكو"))</title>
</head>

<body>
    @await Html.PartialAsync("_NavbarPartial")
    
    @RenderBody()

    @await Html.PartialAsync("_FooterPartial")

    <script src="~/website/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @await Component.InvokeAsync("NToastNotify")
</body>

</html>

KorsatkoApp/Views/Shared/_LoggedInLayout.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<Student> SignInManager
@inject UserManager<Student> UserManager


@{
    var student = (await UserManager.FindByEmailAsync(User.Identity?.Name!));
    var profileHref = student.Gender switch {
        'm' => Href("~/website/img/profile/1.jpg"),
        'f' => Href("~/website/img/profile/2.jpg"),
        _ => Href("~/website/img/profile/1.jpg")
    };
}

<!doctype html>
<html lang="ar" dir="rtl">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cairo&family=Noto+Kufi+Arabic:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/website/css/bootstrap.rtl.min.css">
    <!-- FontAwesome -->
    <link rel="stylesheet" href="~/website/plugins/fontawesome6/css/fontawesome.min.css">
    <link rel="stylesheet" href="~/website/plugins/fontawesome6/css/regular.min.css">
    <link rel="stylesheet" href="~/website/plugins/fontawesome6/css/solid.min.css">

    @await RenderSectionAsync("Styles", required: false)

    <!-- Website CSS -->
    <link rel="stylesheet" href="~/website/css/style.css">

    <title>@(ViewData["Title"] == null ? "كورساتكو" : (ViewData["title"] + " - كورساتكو"))</title>
</head>

<body>
    <div class="wrapper">
        <div class="sidebar-wrapper">
            <div class="sidebar justify-content-sm-between">
                <div class="d-flex flex-row-reverse flex-sm-column">
                <div class="profile">
                    <button type="button" data-bs-toggle="dropdown">
                        <img src="@profileHref" alt="Profile Picture">
                    </button>
                    <ul class="dropdown-menu border-0 shadow-sm">
                        <li>
                            <div class="dropdown-header rounded-top">@student?.FullName</div>
                        </li>

                        <li>
                            <a asp-area="" asp-controller="MyProfile" asp-action="Index" class="dropdown-item">
                                <i class="fa-solid fa-user"></i>
                                <span>صفحتي الشخصية</span>
                            </a>
                        </li>

                        <li>
                            <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                <a onclick="this.parentNode.submit();" class="dropdown-item" style="cursor:pointer">
                                    <i class="fa-solid fa-right-from-bracket"></i>
                                    <span>تسجيل الخروج</span>
                                </a>
                            </form>
                        </li>
                    </ul>
                </div>
                    @if (SignInManager.IsSignedIn(User) && User.IsInRole("User"))
                    {
                        <ul class="nav flex-column">
                            <li class="nav-item">
                                <a asp-controller="MyCourses" asp-action="Index" class="sidebar-item">
                                    <div class="icon">
                                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
                                             width="36" height="33.241" viewBox="0 0 36 33.241">
                                            <defs>
                                                <filter id="event_list_FILL1_wght100_GRAD0_opsz24" x="0" y="0" width="36"
                                                        height="33.241" filterUnits="userSpaceOnUse">
                                                    <feOffset dy="2" input="SourceAlpha" />
                                                    <feGaussianBlur stdDeviation="2" result="blur" />
                                                    <feFlood flood-opacity="0.078" />
                                                    <feComposite operator="in" in2="blur" />
                                                    <feComposite in="SourceGraphic" />
                                                </filter>
                                            </defs>
                                            <g transform="matrix(1, 0, 0, 1, 0, 0)"
                                               filter="url(#event_list_FILL1_wght100_GRAD0_opsz24)">
                                                <path id="event_list_FILL1_wght100_GRAD0_opsz24-2"
                                                      data-name="event_list_FILL1_wght100_GRAD0_opsz24"
                                                      d="M147.862-766.759V-774.9H156v8.138ZM132-770.345v-.966h11.034v.966Zm15.862-9.517V-788H156v8.138ZM132-783.448v-.965h11.034v.965Z"
                                                      transform="translate(-126 792)" fill="currentColor" />
                                            </g>
                                        </svg>
                                    </div>

                                    <div class="title">
                                        دوراتي
                                    </div>
                                </a>
                            </li>

                            <li class="nav-item">
                                <a asp-controller="MyCourses" asp-action="Sessions" class="sidebar-item">
                                    <div class="icon">
                                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
                                             width="36" height="39.584" viewBox="0 0 36 39.584">
                                            <defs>
                                                <filter id="date_range_FILL1_wght100_GRAD0_opsz24" x="0" y="0" width="36"
                                                        height="39.584" filterUnits="userSpaceOnUse">
                                                    <feOffset dy="2" input="SourceAlpha" />
                                                    <feGaussianBlur stdDeviation="2" result="blur" />
                                                    <feFlood flood-opacity="0.078" />
                                                    <feComposite operator="in" in2="blur" />
                                                    <feComposite in="SourceGraphic" />
                                                </filter>
                                            </defs>
                                            <g transform="matrix(1, 0, 0, 1, 0, 0)"
                                               filter="url(#date_range_FILL1_wght100_GRAD0_opsz24)">
                                                <path id="date_range_FILL1_wght100_GRAD0_opsz24-2"
                                                      data-name="date_range_FILL1_wght100_GRAD0_opsz24"
                                                      d="M177.766-823.091a1.045,1.045,0,0,1-.76-.331,1.045,1.045,0,0,1-.331-.76,1.045,1.045,0,0,1,.331-.76,1.045,1.045,0,0,1,.76-.331,1.045,1.045,0,0,1,.76.331,1.045,1.045,0,0,1,.331.76,1.045,1.045,0,0,1-.331.76A1.045,1.045,0,0,1,177.766-823.091Zm6.234,0a1.045,1.045,0,0,1-.76-.331,1.045,1.045,0,0,1-.331-.76,1.045,1.045,0,0,1,.331-.76,1.045,1.045,0,0,1,.76-.331,1.045,1.045,0,0,1,.76.331,1.045,1.045,0,0,1,.331.76,1.045,1.045,0,0,1-.331.76A1.045,1.045,0,0,1,184-823.091Zm6.234,0a1.045,1.045,0,0,1-.76-.331,1.045,1.045,0,0,1-.331-.76,1.045,1.045,0,0,1,.331-.76,1.045,1.045,0,0,1,.76-.331,1.045,1.045,0,0,1,.76.331,1.045,1.045,0,0,1,.331.76,1.045,1.045,0,0,1-.331.76A1.045,1.045,0,0,1,190.234-823.091ZM172-812.416v-24h5.455V-840H178.7v3.584h10.753V-840h1.091v3.584H196v24Zm1.091-1.091h21.818v-14.338H173.091Z"
                                                      transform="translate(-166 844)" fill="currentColor" />
                                            </g>
                                        </svg>
                                    </div>

                                    <div class="title">
                                        مواعيدي
                                    </div>
                                </a>
                            </li
                        </ul>
                    }
                </div>

                @if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                {
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="sidebar-item">
                                <div class="icon">
                                    <svg xmlns="http://www.w3.org/2000/svg" height="36" viewBox="0 -960 960 960" width="36">
                                        <path fill="currentColor" d="M680-280q25 0 42.5-17.5T740-340q0-25-17.5-42.5T680-400q-25 0-42.5 17.5T620-340q0 25 17.5 42.5T680-280Zm0 120q31.769 0 57.385-14.115 25.615-14.116 42.384-38.116Q757-226 732-233q-25-7-52-7t-52 7q-25 7-47.769 20.769 16.769 24 42.384 38.116Q648.231-160 680-160Zm-200 38.462q-120.539-35.769-200.269-146.039Q200-377.846 200-516v-216.308l280-104.615 280 104.615v226.231q-9-3.385-19.769-6.039Q729.462-514.769 720-517v-187.769L480-794l-240 89.231V-516q0 59.308 17.5 113.615 17.5 54.308 47.692 99.885 30.192 45.577 71.423 79.654t87.923 51.923l2.308-.769q4.846 12 12.077 23.307 7.231 11.308 16.385 21.231-4.077 1.539-7.654 2.808T480-121.538ZM680-120q-66.846 0-113.423-46.577T520-280q0-66.846 46.577-113.423T680-440q66.846 0 113.423 46.577T840-280q0 66.846-46.577 113.423T680-120ZM480-482.462Z" />
                                    </svg>
                                </div>

                                <div class="title">
                                    لوحة التحكم
                                </div>
                            </a>
                        </li>
                    </ul>
                }
            </div>
        </div>

        <div class="page-wrapper">
            @await Html.PartialAsync("_NavbarPartial")

            @RenderBody()

            @await Html.PartialAsync("_FooterPartial")
        </div>
    </div>

    <script src="~/website/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @await Component.InvokeAsync("NToastNotify")
</body>

</html>

KorsatkoApp/Views/Shared/_NavbarPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<Student> SignInManager


<nav class="navbar navbar-expand-md mx-sm-3">
    <div class="d-flex w-100 justify-content-between container-fluid">
        <a href="/" class="navbar-brand">
            <div class="brand-container drop-shadow">
                <img src="~/website/img/k-logo-t.png" alt="Korsatko" height="28">
            </div>
        </a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mainNav">
            <i class="fa-solid fa-bars"></i>
        </button>

        <div class="collapse navbar-collapse me-auto mb-2 mb-md-0" id="mainNav">
            <div class="w-100 d-md-flex justify-content-between">
                <div class="">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Home" asp-action="Index"
                               class="nav-link @(ViewBag.activeNavbarItem == "home" ? "active" : "")">
                                الصفحة الرئيسية
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Home" asp-action="Courses"
                                class="nav-link @(ViewBag.activeNavbarItem == "courses" ? "active" : "")">
                                الدورات
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Home" asp-action="Instructors"
                                class="nav-link @(ViewBag.activeNavbarItem == "instructors" ? "active" : "")">
                                المدربين
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Home" asp-action="AboutUs"
                                class="nav-link @(ViewBag.activeNavbarItem == "aboutUs" ? "active" : "")">
                                من نحن
                            </a>
                        </li>
                    </ul>
                </div>
                
                @if (!SignInManager.IsSignedIn(User))
                {
                    <div class="d-block">
                        <div class="pt-md-1 pt-4 d-flex justify-content-center justify-content-md-end">
                            <a asp-area="Identity" asp-page="/Account/Login" class="btn py-2 py-md-1 fw-light">
                                تسجيل الدخول
                            </a>

                            <a asp-area="Identity" asp-page="/Account/Register" class="btn btn-primary fw-light py-2 px-3 py-md-1 px-md-3">
                                انضم إلينا
                            </a>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</nav>